# More info: https://www.spigotmc.org/resources/smoothsleep.32043
enable-stats: true
enable-data-share: true
update-notify-login: false
logging-settings:
  log-debug: false
  log-warning: true
  log-info: true
worlds:
  world:
    min-night-speed-mult: 10
    max-night-speed-mult: 20
    night-speed-curve: 0.5
    morning-sound: 'ENTITY_PLAYER_LEVELUP'
    morning-particle-options:
      particle: 'VILLAGER_HAPPY'
      amount: 20
      radius: 0.5
      enabled: true
      delay-ticks: 5
      pattern: 'RANDOM'
    instant-day-if-all-sleeping: false
    essentials-settings:
      ignore-afk: true
      ignore-vanish: true
    replenish-settings:
      heal-negative-statuses: true
      hours-to-heal-negative: 3
      heal-positive-statuses: false
      hours-to-heal-positive: 3
      ticks-per-heal: 1000
      heal-amount: 0
      heal-awake: false
      ticks-per-feed: 1000
      feed-amount: 0
      feed-awake: false
    sleep-rewards:
      potion-effects:
        enabled: true
        required-hours-sleep: 3
        show-effect-particles: false
        effects:
          LUCK:
            duration: 3600
            amplifier: 0
    clear-weather-when-morning: true
    titles:
      enabled: true
      sleep-title: '&b{12H}:{MIN} {MER_UPPER}'
      sleep-subtitle: '&a{SLEEPERS}/{TOTAL} Sleeping &3({TIMESCALE}x speed)'
      morning-title: '&e{12H}:{MIN} {MER_UPPER}'
      morning-subtitle: '&aRise and shine, {USERNAME}!'
      stay-ticks: 20
      fade-ticks: 40
    action-bar:
      enabled: true
      show-if-awake: false
      title: '&4Health: &c{HEALTH_BAR} &3Food: &b{FOOD_BAR}'
    boss-bar:
      enabled: true
      show-if-awake: true
      color: 'BLUE'
      title: '&a{SLEEPERS}/{TOTAL} Sleeping &3- &b{12H}:{MIN} {MER_UPPER}'